name: calories
description: "Food suggestion app"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.8.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_sficon: ^1.2.1
  is_first_run: ^1.0.0
  shared_preferences: ^2.5.3
  openfoodfacts: ^3.27.0
  permission_handler: ^12.0.1
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  freezed_annotation: ^3.1.0
  path_provider: ^2.1.5
  dio: ^5.9.0
  http: ^1.6.0
  riverpod_annotation: ^3.0.3
  flutter_riverpod: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  hive_ce_generator: ^1.8.1
  build_runner: ^2.7.1
  freezed: ^3.2.3
  freezed_lint: ^0.0.12
  riverpod_generator: ^3.0.3
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.otf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Inter-Light.otf
          weight: 300
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Inter-Black.otf
          weight: 900
